name: strict_flutter_lints
description: A rigorous collection of flutter linter rules that's gonna make your codebase crystal clear.
repository: https://github.com/erfactor/strict_flutter_lints
version: 1.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_lints: ^2.0.1
  dart_code_metrics: ^5.2.1
